# Credential of google cloud
CREDENTIAL_PATH = 

RESUME_PATH_1 = 
RESUME_PATH_2 =
RESUME_PATH_3 = 
RESUME_PATH_4 = 

SUBJECT_LIST = 
LOCAL_RESUME_KEYWORDS_BUCKET = 
LOCAL_RESUME_KEYWORDS_NAME = 
LOCAL_JOB_KEYWORDS_BUCKET = 
LOCAL_JOB_KEYWORDS_NAME = 
